baseurl = "https://hx765.github.io"
title = "Han Xiao's blog"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = ""
  description = "Han Xiao's blog"
  keyword = ""
  slogan = ""

  image_404 = ""
  title_404 = ""

  # leancloud storage for page view counter
  page_view_conter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Learner, High mover"
  sidebar_avatar = ""      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true
  featured_condition_size = 1

  # Baidu Analytics
  ba_track_id = ""

  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles
  reward = false
  # reward_guide = "如果这篇文章对你有用,请随意打赏"

  friends = true
  bookmarks = false
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  # Highlight.js theme
  # demo: https://highlightjs.org/static/demo/
  highlightjs = "docco"

  [params.social]
  rss            = false
  email          = "hannyc@seas.upenn.edu"
  linkedin       = "https://www.linkedin.com/in/hanxiaocpa"
  github         = "https://github.com/hx765"


  [[params.friend_link]]
  title = "Zhenyu Tian"
  href =  "https://zhenyutian.com"

  [[params.bookmark_link]]
  title =  "Coursera"
  href =  "https://www.coursera.com"

  [[params.addtional_menus]]
  title =  "POST"
  href =  "/POST"
  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]
