baseurl = "https://hx765.github.io"
title = "Han's Blog"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname

[outputs]
#home = ["HTML", "RSS", "Algolia"]

[params]
  #header_image = "img/home-bg-jeep.jpg"
  #SEOTitle = "赵化冰的博客 | Zhaohuabing Blog"
  description = "Blog"
  #keyword = "add keyword"
  #slogan = "add slogan"

  #image_404 = "img/404-bg.jpg"
  #title_404 = "你来到了没有知识的荒原 :("

  # leancloud storage for page view counter
  #page_view_conter = true
  #leancloud_app_id = "Xu5MAnXL360Ms89vMVnWBjuq-gzGzoHsz"
  #leancloud_app_key = "efUYEefAc2eIPBRO59PRERQC"

  # Sidebar settings
  sidebar_about_description = "contact me↓"
  #sidebar_avatar = "img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  #sidebar_avatar = "img/zhaohuabing.png"      # use absolute URL, seeing it's used in both `/` and `/about/`

  #featured_tags = true
  #featured_condition_size = 2

  # We need a proxy to access Disqus api in China
  #disqus_proxy = "https://disqusapi.zhaohuabing.com"
  #disqus_site = "https://zhaohuabing.com"

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles
  #reward = true
  #reward_guide = "嗯，这篇文章对我有用，鼓励一下..."

  friends = true
  bookmarks = true
  about_me = true

  [params.social]
  rss            = true
  email          = "hannyc@seas.upenn.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  linkedin       = "https://www.linkedin.com/in/hanxiaocpa"
  #stackoverflow  = "full url"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/HX765"
  #wechat        = "full profile url "
  #medium        = "full profile url "
  #pinterest     = "full profile url in pinterest"

  [[params.friend_link]]
  title = "Zhenyu Tian"
  href =  "https://zhenyutian.com"
